### ISSUE TITLE
How did you crop the hand region

### ISSUE THREAD

**Issue by quyanqiu** [arielai/youtube_3d_hands#1]
Hi,Thanks for the kindness sharing for the youtube 3D  dataset.
As the data format you provide,The annotation did not contain hand bounding box information,so I am curious about the way you crop hand region from the original youtube video. Did you just use openpose to detect keypoints and use the tightest bounding box enclosing all hand joints?Or use some hand detection algorithm to crop the hand region?

**Comment by quyanqiu** [comment]
problem solved，just use the vertices min and max x,y coordinate because these vertices has been total aligned to the original image.

**Comment by dkulon** [comment]
@quyanqiu Yes, that's exactly how we obtain a bounding box from vertex annotations.

**Comment by quyanqiu** [comment]
@dkulon Hi sorry for bothering you again,How did you normalize the mesh in training labels,Did you simply  minus mean value of xyz coordinate and divide it with std value of xyz ?

**Comment by dkulon** [comment]
@quyanqiu Yes, please note that these values change depending on the image crop size.

**Comment by quyanqiu** [comment]
@dkulon There is another question,I successfully train the whole network based on youtube3D dataset, But the network did not perform well for the freiHand training samples，So I would like to fintune the network by using FreiHand training data.But the verts annotation for the FreiHand did not align to the image space,My question is how to align the verts label of FreiHand to its provided rgb images?
Appreciate if you can help again!

**Comment by dkulon** [comment]
@quyanqiu 

1) Project the points using the camera parameters listed in the dataset.
2) Take X, Y coordinates and reconstruct the depth as follows:

```
        # v_world is the FreiHAND mesh in the world coordinates.
        # proj_x is the projected mesh in the image coordinates.
        # projectPoints is taken from the FreiHAND source code and K is the intrinsic matrix.

        proj_x = projectPoints(v_world, K)

        s_x = np.std(proj_x[:, 0]) / np.std(v_world[:, 0])
        z_cam = s_x *(v_world[:, 2]).reshape(-1, 1)
        V = np.concatenate((proj_x[:, :2], z_cam), axis=1)
```

**Comment by quyanqiu** [comment]
@dkulon
Thanks so much for providing the code here.
I will definitely try it!

**Comment by SuhelNaryal** [comment]
@quyanqiu Hi, Can you share your trained model?

**Comment by SuhelNaryal** [comment]
@quyanqiu Hi, Can you share your trained model?
