### ISSUE TITLE
Problems in dataset request form

### ISSUE THREAD

**Issue by TneitaP** [arielai/youtube_3d_hands#10]
Hi, the link of the dataset request form (https://forms.gle/U385D7b7Qfrig9NR9) is not avaliable for me on Chrome. Please verify it again,  thank you !

**Comment by dkulon** [comment]
Hi @TneitaP, I cannot reproduce your issue. Maybe you can try a full link:
https://docs.google.com/forms/d/e/1FAIpQLScxRLH8roH8_61CPnwOp6aSnFvmbWD50wbnsTiTKgXn0UIaEQ/viewform

**Comment by TneitaP** [comment]
Thank you for your swift reply, the problem has been solved perfectly ~

**Comment by dkulon** [comment]
:)
