### ISSUE TITLE
full annotations request

### ISSUE THREAD

**Issue by namepllet** [arielai/youtube_3d_hands#17]
I'm currently working on your dataset.

In annotation files, there only exists part of annotation (not for all frames in video) and vertex coordinate is saved as 2.5D coordinate(x,y coordinate in image space).

So, I'm wondering if I can get whole annotation file that cover above mentioned problems. (Annotations for all frames, 3D coordinate for mesh vertices or MANO parameters)

**Comment by dkulon** [comment]
Hi @namepllet, we are not planning to release additional annotations.
