### ISSUE TITLE
How did you get the camera parameters? 

### ISSUE THREAD

**Issue by lixiny** [arielai/youtube_3d_hands#2]
Thanks for sharing the great youtube 3D dataset.
where did you put the camera parameters in Youtube 3D when project vertices from 3d to pixel planes?

**Comment by dkulon** [comment]
Hi @lixiny, the estimation method is described in Section 3 of the paper. We do not publish the estimated camera parameters or non-aligned meshes.

**Comment by quyanqiu** [comment]
@lixiny If my understanding is not wrong， you may check https://github.com/vchoutas/smplify-x for more details

**Comment by lixiny** [comment]
Thanks for your quick response @dkulon @quyanqiu , I will close this issue.
