### ISSUE TITLE
Dataset Access

### ISSUE THREAD

**Issue by NANWOOD** [arielai/youtube_3d_hands#24]
I have followed the guidelines provided on GitHub and submitted the dataset request form as instructed. However, I have not received a response regarding my request. It seems the email address is not valid now. Could you please provide an update on the status of my request or any additional information on the process?

**Comment by dkulon** [comment]
Hi @NANWOOD,

I just processed all requests so you should receive an email with an access link.

**Comment by NANWOOD** [comment]
Thanks a lot!
