### ISSUE TITLE
about get dataset

### ISSUE THREAD

**Issue by www516717402** [arielai/youtube_3d_hands#6]
Hello, great project. I did not receive any email when write Dataset Request Form for academic research about a week ago.Hope your reply. email www516717402@gmail.com

**Comment by dkulon** [comment]
Hi @www516717402 , we require an academic email address to send the dataset access link (e.g. ending with .edu.cn). If you submit a form with a valid email address, you will be granted access permissions in a day or two (the email can go to a spam folder).
