### ISSUE TITLE
invalid Data link

### ISSUE THREAD

**Issue by lingtengqiu** [arielai/youtube_3d_hands#7]
Hello, I am very interested in your work. However, The dataset link request that is likely to be invalid. Could you please give your datasets link.

I hope for your reply.

best 

Qiu

**Comment by dkulon** [comment]
Hi @lingtengqiu,

The dataset request form works correctly. The access permission link is not sent automatically. Each request is processed by someone. 

Please, note that you need to use an academic email address as well (e.g. ending with .edu.cn) to receive a reply. 

Best,
Dominik
